### PR TITLE
Little change in user fetching and update.

### PR DESCRIPTION
**Pull request by aksr-aashish**

### CODE REVIEW

**Review by xenmods — COMMENTED** [review]
1800 seconds is 30 minutes. That is too much.  1 minute won't affect the performance as it is just 1 request per minute.

**Review by SOME-1HING — COMMENTED** [review]
60 seconds was fine.

**Comment by SOME-1HING** [comment]
The only thing that changed is optimisation in scanner.py, which I already approved in the last pull request. So that will be pulled in v1.0.8.

**Comment by xenmods** [comment]
How is it useless loading it every minute? 
If I scanned a user 20mins ago. The user still won't be banned until the list updates after 30 minutes. 1 request per minute is very less and does not affect the bot's performance. Maybe increase it to 3-5 mins but I'd still suggest 1 minute.

**Comment by SOME-1HING** [comment]
Decide on example.py, and after that make a pull request for that.

**Pull request closed without merging**
